apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: kulikov
spec:
  selector:
    matchLabels:
      app: kibana
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.2.0
        env:
          - name: ELASTICSEARCH_HOSTS
            value: http://sts-elasticsearch-0.svc-elasticsearch.kulikov.svc.cluster.local:9200
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 5601


