apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
  namespace: kulikov
spec:
  selector:
    matchLabels:
      app: redis-slave
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-slave
    spec:
      containers:
      - name: redis-slave
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        command:
          - "/bin/bash"
          - "-c"
          - "redis-server"
          - "--slaveof"
          - "redis-master.kulikov.svc.cluster.local"
          - "6379"
        ports:
        - containerPort: 6379