kind: Service
apiVersion: v1
metadata:
  name: kibana
  namespace: kulikov
  labels:
    app: kibana
spec:
  ports:
  - name: http
    port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    app: kibana
  type: ClusterIP