apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: kulikov
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis-master
  sessionAffinity: None
  type: ClusterIP